-- AlterTable
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "password" VARCHAR(255);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "name" VARCHAR(100);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "gender" VARCHAR(10);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "birthday" TIMESTAMP(3);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "email" VARCHAR(255);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "bio" TEXT;

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "users_email_key" ON "users"("email");
